[package]
name = "crawlstack"
version = "0.1.0"
edition = "2021"
authors = ["Rich-T-kid"]
description = "An inverted web scraping index written in Rust"
license = "MIT"
repository = "https://github.com/Rich-T-kid/CrawlStack"

[dependencies]
axum = "0.8.7"
reqwest = "0.12.24"
scraper = "0.24.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.48.0", features = ["full", "rt-multi-thread"] }
